config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
    get '/logout', to: 'application#logout', as: :logout_author
    get '/login', to: 'application#login', as: :login_author


  get '/search_directory', to:  'ldap_lookup#ldap_lookups', as: :ldap_lookup
  get '/committee_select', to: 'ldap_lookup#committee_select', as: :committee_select

  namespace :admin do
    resources :programs, except: [:show, :destroy]
    resources :degrees,  except: [:show, :destroy]
    resources :authors,  except: [:new, :create, :show, :destroy]

    get '/submissions/:id/edit', to: 'submissions#edit', as: :edit_submission
    delete '/submissions', to: 'submissions#bulk_destroy', as: :delete_submissions

    patch '/submissions/:id/format_review_response', to: 'submissions#record_format_review_response', as: :submissions_format_review_response
    patch '/submissions/:id/final_submission_response', to: 'submissions#record_final_submission_response', as: :submissions_final_submission_response

    get '/:degree_type', to: 'submissions#dashboard', as: :submissions_dashboard

    get '/:degree_type/:scope', to: 'submissions#index', as: :submissions_index

    patch '/:degree_type/final_submission_approved', to: 'submissions#release_for_publication', as: :submissions_release_final_submission_approved

    root to: redirect(path: "/admin/#{Degree.default_degree_type}"), as: :dashboard
  end

  namespace :author do
    resources :authors, except: [:index, :show, :destroy]
    resources :submissions, except: [:show] do
      get '/program_information', to: 'submissions#program_information', as: :program_information

      get '/committee', to: 'submissions#committee', as: :committee

      get '/format_review', to: 'submissions#format_review', as: :format_review
      get '/format_review/edit', to: 'submissions#edit_format_review', as: :edit_format_review
      patch '/format_review', to: 'submissions#update_format_review', as: :update_format_review

      get '/final_submission', to: 'submissions#final_submission', as: :final_submission
      get '/final_submission/edit', to: 'submissions#edit_final_submission', as: :edit_final_submission
      patch '/final_submission', to: 'submissions#update_final_submission', as: :update_final_submission

#      get 'committee/lookup_member(:access_id)(:last_name)', to: 'submissions#lookup_committee_member', as: :lookup_member

      resource :committee, except: [:show, :destroy]


    end
    root to: 'submissions#index'
  end

  root :to => 'static#home'

  get    '/mockups/:page' => 'mockups#show', as: :mockup

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-12">
      <div class="alert alert-danger">
        <ul>
          <% for message in object.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_file_fields.html.erb
<div class="nested-fields">
  <% if file_fields.object.asset? %>
    <div id="<%= file_fields.object.class_name %>-<%= file_fields.object.id %>" class="form-group uploaded-file-link">
      <%= file_fields.input :asset, as: :hidden %>
      <%= link_to_remove_association "[delete]", file_fields, class: 'text-danger can-toggle-clickability' %>
      <%= link_to file_fields.object.asset_identifier, file_fields.object.asset_url, class: 'file-link', target: '_blank' %>
    </div>
  <% else %>
    <%= file_fields.input :asset, as: :file, label: false %>
    <%= link_to_remove_association "[remove]", file_fields, class: 'text-danger' %>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>

  <% key == 'alert' ? key = 'danger' : key = 'success' %>

  <div class="alert alert-<%= key %> alert-dismissable">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <button type="button" class="close" aria-hidden="true">&times;</button>
          <%= value %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/shared/_header.html.erb
<header>
  <div id="shield-and-logo">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <a id="psu-shield" href="http://psu.edu/">
            <%= image_tag 'penn-state-mark.svg', alt: 'PSU logo', height: '60px' %>
          </a>
        <span id="logo">
          <a href="/">Electronic Theses and Dissertations</a>
        </span>
        </div>
      </div>
    </div>
  </div>

  <nav id="account-navigation" class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <button type="button" class="navbar-toggle pull-left" data-toggle="collapse" data-target="#main-navigation">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="pull-right">
            <span class="navbar-text small hidden-xs">Logged in as <%= @author.full_name %> </span>
            <%= link_to 'Log Out', :logout_author, :class=>"btn btn-default btn-sm navbar-btn" %>
          </div>
        </div>
        <!-- /.col-* -->
      </div>
    </div>
  </nav>

  <% if flash %>
    <%= render partial: 'shared/flash_messages' %>
  <% end %>

</header>

app/views/shared/_main_navigation.html.erb
<nav id="main-navigation" class="collapse navbar-collapse">
  <ul class="nav nav-pills nav-stacked" role="navigation">
    <li class="<%= 'active' if current_page? root_path %>" >
      <%= link_to 'Dashboard', root_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'authors' %>" >
      <%= link_to 'Authors', admin_authors_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'programs' %>" >
      <%= link_to 'Programs', admin_programs_path %>
    </li>
    <li class="<%= 'active' if controller_name == 'degrees' %>" >
      <%= link_to 'Degrees', admin_degrees_path %>
    </li>
  </ul>
</nav>