config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
    get '/logout', to: 'application#logout', as: :logout_author
    get '/login', to: 'application#login', as: :login_author


  get '/search_directory', to:  'ldap_lookup#ldap_lookups', as: :ldap_lookup
  get '/committee_select', to: 'ldap_lookup#committee_select', as: :committee_select

  namespace :admin do
    resources :programs, except: [:show, :destroy]
    resources :degrees,  except: [:show, :destroy]
    resources :authors,  except: [:new, :create, :show, :destroy]

    get '/submissions/:id/edit', to: 'submissions#edit', as: :edit_submission
    delete '/submissions', to: 'submissions#bulk_destroy', as: :delete_submissions

    patch '/submissions/:id/format_review_response', to: 'submissions#record_format_review_response', as: :submissions_format_review_response
    patch '/submissions/:id/final_submission_response', to: 'submissions#record_final_submission_response', as: :submissions_final_submission_response

    get '/:degree_type', to: 'submissions#dashboard', as: :submissions_dashboard

    get '/:degree_type/:scope', to: 'submissions#index', as: :submissions_index

    patch '/:degree_type/final_submission_approved', to: 'submissions#release_for_publication', as: :submissions_release_final_submission_approved

    root to: redirect(path: "/admin/#{Degree.default_degree_type}"), as: :dashboard
  end

  namespace :author do
    resources :authors, except: [:index, :show, :destroy]
    resources :submissions, except: [:show] do
      get '/program_information', to: 'submissions#program_information', as: :program_information

      get '/committee', to: 'submissions#committee', as: :committee

      get '/format_review', to: 'submissions#format_review', as: :format_review
      get '/format_review/edit', to: 'submissions#edit_format_review', as: :edit_format_review
      patch '/format_review', to: 'submissions#update_format_review', as: :update_format_review

      get '/final_submission', to: 'submissions#final_submission', as: :final_submission
      get '/final_submission/edit', to: 'submissions#edit_final_submission', as: :edit_final_submission
      patch '/final_submission', to: 'submissions#update_final_submission', as: :update_final_submission

#      get 'committee/lookup_member(:access_id)(:last_name)', to: 'submissions#lookup_committee_member', as: :lookup_member

      resource :committee, except: [:show, :destroy]


    end
    root to: 'submissions#index'
  end

  root :to => 'static#home'

  get    '/mockups/:page' => 'mockups#show', as: :mockup

end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < AdminController

  def dashboard
    @view = Admin::SubmissionsDashboardView.new(params[:degree_type])
  end

  def edit
    @submission = Submission.find(params[:id])
    @view = Admin::SubmissionFormView.new(@submission, session)
  end

  def index
    session[:return_to] = request.referer
    @view = Admin::SubmissionsIndexView.new(params[:degree_type], params[:scope])
  end

  def bulk_destroy
    ids = params[:submission_ids].split(',')
    Submission.destroy(ids)
    flash[:notice] = 'Submissions deleted successfully'
    redirect_to session.delete(:return_to)
  rescue
    flash[:alert] = 'There was a problem deleting your submissions'
    redirect_to session.delete(:return_to)
  end

  def release_for_publication
    ids = params[:submission_ids].split(',')
    Submission.release_for_publication(ids)
    flash[:notice] = 'Submissions released successfully'
    redirect_to admin_submissions_dashboard_path(params[:degree_type])
  rescue SubmissionStatusGiver::AccessForbidden
    flash[:alert] = 'There was a problem releasing the submissions, please try again.'
    redirect_to session.delete(:return_to)
  end

  def record_format_review_response
    @submission = Submission.find(params[:id])
    if params[:approved]
      status_giver = SubmissionStatusGiver.new(@submission)
      status_giver.can_respond_to_format_review?
      @submission.update_attributes!(format_review_params)
      status_giver.collecting_final_submission_files!
      @submission.update_attribute :format_review_approved_at, Time.zone.now
      redirect_to admin_submissions_index_path(@submission.parameterized_degree_type, 'format_review_submitted')
      flash[:notice] = 'The submission\'s format review information was successfully approved and returned to the author to collect final submission information.'
    end
    if params[:rejected]
      status_giver = SubmissionStatusGiver.new(@submission)
      status_giver.can_respond_to_format_review?
      @submission.update_attributes!(format_review_params)
      status_giver.collecting_format_review_files!
      @submission.update_attribute :format_review_rejected_at, Time.zone.now
      redirect_to admin_submissions_index_path(@submission.parameterized_degree_type, 'format_review_submitted')
      flash[:notice] = 'The submission\'s format review information was successfully rejected and returned to the author for revision.'
    end
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s format review information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that the submission\'s format review information is correct.'
  end

  def record_final_submission_response
    @submission = Submission.find(params[:id])
    if params[:approved]
      status_giver = SubmissionStatusGiver.new(@submission)
      status_giver.can_respond_to_final_submission?
      @submission.update_attributes!(final_submission_params)
      status_giver.waiting_for_publication_release!
      @submission.update_attribute :final_submission_approved_at, Time.zone.now
      redirect_to admin_submissions_index_path(@submission.parameterized_degree_type, 'final_submission_submitted')
      flash[:notice] = 'The submission\'s final submission information was successfully approved.'
    end
    if params[:rejected]
      status_giver = SubmissionStatusGiver.new(@submission)
      status_giver.can_respond_to_final_submission?
      @submission.update_attributes!(final_submission_params)
      status_giver.collecting_final_submission_files!
      @submission.update_attribute :final_submission_rejected_at, Time.zone.now
      redirect_to admin_submissions_index_path(@submission.parameterized_degree_type, 'final_submission_submitted')
      flash[:notice] = 'The submission\'s final submission information was successfully rejected and returned to the author for revision.'
    end
  rescue ActiveRecord::RecordInvalid
    @view = Admin::SubmissionFormView.new(@submission, session)
    render :edit
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to session.delete(:return_to)
    flash[:alert] = 'This submission\'s final submission information has already been evaluated.'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to session.delete(:return_to)
    flash[:alert] = 'Oops! You may have submitted invalid final submission data. Please check that the submission\'s final submission information is correct.'
  end

  private

  def format_review_params
    params.require(:submission).permit(:semester,
                                       :year,
                                       :author_id,
                                       :program_id,
                                       :degree_id,
                                       :title,
                                       :format_review_notes,
                                       committee_members_attributes: [:role, :name, :email, :is_advisor, :id],
                                       format_review_files_attributes: [:asset, :id, :_destroy])
  end

  def final_submission_params
    params.require(:submission).permit(:semester,
                                       :year,
                                       :author_id,
                                       :program_id,
                                       :degree_id,
                                       :title,
                                       :format_review_notes,
                                       :final_submission_notes,
                                       :defended_at,
                                       :abstract,
                                       :keywords,
                                       :access_level,
                                       committee_members_attributes: [:role, :name, :email, :is_advisor, :id],
                                       format_review_files_attributes: [:asset, :id, :_destroy],
                                       final_submission_files_attributes: [:asset, :id, :_destroy])
  end

end

app/controllers/author/submissions_controller.rb
class Author::SubmissionsController < AuthorController

  def index
    @view = Author::SubmissionsIndexView.new(@author)
  end

  def new
    @submission = @author.submissions.new
  end

  def create
    @submission = @author.submissions.new(program_information_params)
    @submission.save!
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.collecting_committee!
    redirect_to author_root_path
    flash[:notice] = 'Program information saved successfully'
  rescue ActiveRecord::RecordInvalid
    render :new
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to author_root_path
    flash[:alert] = 'Oops! You may have submitted invalid program information data. Please check that your program information is correct.'
  end

  def edit
    @submission = @author.submissions.find(params[:id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_update_program_information?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def update
    @submission = @author.submissions.find(params[:id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_update_program_information?
    @submission.update_attributes!(program_information_params)
    redirect_to author_root_path
    flash[:notice] = 'Program information updated successfully'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to edit_author_submission_path(@submission)
    flash[:alert] = e.message
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def destroy
    @submission = @author.submissions.find(params[:id])
    @submission.destroy
    flash[:notice] = "Submission deleted successfully."
    redirect_to author_root_path
  rescue
    flash[:alert] = "Can not delete submission."
    redirect_to author_root_path
  end

  def program_information
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_review_program_information?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def committee
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_review_committee?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def edit_format_review
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_upload_format_review_files?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def update_format_review
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_upload_format_review_files?
    @submission.update_attributes!(format_review_params)
    status_giver.waiting_for_format_review_response!
    @submission.update_attribute :format_review_files_uploaded_at, Time.zone.now
    redirect_to author_root_path
    flash[:notice] = 'Format review files uploaded successfully.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to author_submission_format_review_path(@submission)
    flash[:alert] = e.message
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to author_root_path
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that your format review information is correct.'
  end

  def format_review
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_review_format_review_files?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def edit_final_submission
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_upload_final_submission_files?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  def update_final_submission
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_upload_final_submission_files?
    @submission.update_attributes!(final_submission_params)
    status_giver.waiting_for_final_submission_response!
    @submission.update_attribute :final_submission_files_uploaded_at, Time.zone.now
    redirect_to author_root_path
    flash[:notice] = 'Final submission files uploaded successfully.'
  rescue ActiveRecord::RecordInvalid
    render :edit_final_submission
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  rescue SubmissionStatusGiver::InvalidTransition
    redirect_to author_root_path
    flash[:alert] = 'Oops! You may have submitted invalid format review data. Please check that your format review information is correct.'
  end

  def final_submission
    @submission = @author.submissions.find(params[:submission_id])
    status_giver = SubmissionStatusGiver.new(@submission)
    status_giver.can_review_final_submission_files?
  rescue SubmissionStatusGiver::AccessForbidden
    redirect_to author_root_path
    flash[:alert] = 'You are not allowed to visit that page at this time, please contact your administrator'
  end

  private

  def program_information_params
    params.require(:submission).permit(:semester,
                                       :year,
                                       :author_id,
                                       :program_id,
                                       :degree_id,
                                       :title)
  end

  def format_review_params
    params.require(:submission).permit(:title,
                                       format_review_files_attributes: [:asset, :submission_id, :id, :_destroy])
  end

  def final_submission_params
    params.require(:submission).permit(:defended_at,
                                       :abstract,
                                       :keywords,
                                       :access_level,
                                       :has_agreed_to_terms,
                                       final_submission_files_attributes: [:asset, :submission_id, :id, :_destroy])
  end

end

app/views/admin/submissions/_bulk_actions.html.erb
<div class="row">
  <div class="col-xs-12">
    <div id="bulk-actions">
      <h5>Bulk Actions
        <span class="small"><span class="number-of-selected-rows"></span> submissions selected ( <span class="number-of-visible-selected-rows"></span> visible )</span>
      </h5>

      <div class="actions">
        <%= button_to 'Delete selected', admin_submissions_delete_format_review_incomplete_path,
            method: 'delete',
            params: { submission_ids: '' },
            data: { confirm: "Are you sure you want to permanently delete the selected submission(s)?" },
            class: 'btn btn-danger' %>
        <%= button_to 'Release selected for publication', admin_submissions_release_final_submission_approved_path,
            method: 'patch',
            params: { submission_ids: '' },
            data: { confirm: "Are you sure you want to release the selected submission(s)?" },
            class: 'btn btn-primary' if render_release_for_publication_button == true %>
      </div>
    </div>
    <div id="row-selection-buttons">
      <button class="select-all-button btn btn-sm btn-default">Select All</button>
      <button class="deselect-all-button btn btn-sm btn-default">Deselect All</button>
      <button class="select-visible-button btn btn-sm btn-default">Select Visible</button>
      <button class="deselect-visible-button btn btn-sm btn-default">Deselect Visible</button>
    </div>
  </div>
</div>

app/views/admin/submissions/_file_fields.html.erb
<%#  Since we need this partial in both the admin and author forms,  %>
<%#  and since the cocoon gem requires to have these partials in     %>
<%#  the same directory as their parent template, we will simply     %>
<%#  use these to point to the single shared partial.                %>

<%= render partial: 'shared/file_fields', locals: { file_fields: file_fields } %>

app/views/admin/submissions/_filter.html.erb
<% if filter[:path] %>
  <%= link_to filter[:path], id: filter[:id], class: 'panel panel-default filter' do %>
    <div class='panel-heading'>
      <h3 class='panel-title'><%= filter[:title] %>
        <span class='badge pull-right'><%= filter[:count] %></span>
      </h3>
    </div>
    <div class='panel-body'><%= filter[:description] %></div>
  <% end %>
<% else %>
  <div id="<%= filter[:id] %>" class='panel panel-default no-submissions'>
    <div class='panel-heading'>
      <h3 class='panel-title'><%= filter[:title] %> <span class='badge pull-right'>0</span></h3></div>
    <div class='panel-body'><%= filter[:description] %></div>
  </div>
<% end %>

app/views/admin/submissions/_final_submission_fields.html.erb
<div class="form-section-heading" data-toggle="collapse" data-target="#final-submission-information">Final Submission Information
  <span class="hide-show-indicator fa-rotate-90"></span>
</div>
<div id="final-submission-information" class="form-section-body collapse in">
  <%= f.input :defended_at, as: :date, label: 'Date defended<span class="required-astrisk">*</span>'.html_safe %>
  <%= f.input :abstract, as: :text, label: 'Abstract<span class="required-astrisk">*</span>'.html_safe, input_html: { class: 'can-toggle-editability' } %>
  <%= f.input :keywords, as: :text, label: 'Keywords<span class="required-astrisk">*</span>'.html_safe, input_html: { class: 'can-toggle-editability' } %>
  <%= f.input :access_level, as: :radio_buttons,
      collection: [['Open Access', 'open_access'], ['Restricted (Penn State only)', 'restricted_to_institution'],['Restricted', 'restricted']],
      wrapper: :vertical_radio_and_checkboxes,
      label: 'Access level<span class="required-astrisk">*</span>'.html_safe %>

  <div class="links cocoon-links">
    <label>Final Submission Files<span class="required-astrisk">*</span></label>
    <%= link_to_add_association f, :final_submission_files,
        class: 'btn btn-default btn-sm can-toggle-clickability',
        data: { association_insertion_node: '#final-submission-file-fields', association_insertion_method: 'append' },
        form_name: 'file_fields',
        partial: 'file_fields' do %>
      <span class="glyphicon glyphicon-plus"></span> Additional File
    <% end %>
  </div>
  <div id="final-submission-file-fields">
    <%= f.simple_fields_for :final_submission_files do |final_submission_file| %>
      <%= render 'file_fields', file_fields: final_submission_file %>
    <% end %>
  </div>

  <%= f.input :final_submission_notes, as: :text, label: "Final Submission Notes to Student<span title='require' class='required-asterisk'>*</span>".html_safe, input_html: { class: 'can-toggle-editability' } %>

  <% if @submission.beyond_waiting_for_final_submission_response? %>
    <%= link_to '#', class: 'form-edit-link toggle-link' do %>
      <span class="fa"></span> <span class="verb">Edit</span> Final Submission Information
    <% end %>
  <% end %>
</div>

app/views/admin/submissions/_format_review_file_fields.html.erb
<div class="nested-fields">
  <% if file_fields.object.filename? %>
    <div class="form-group uploaded-file-link">
      <%= link_to_remove_association "[delete]".html_safe, file_fields, class: 'text-danger' %>
      <%= link_to file_fields.object.filename_identifier, file_fields.object.filename_url, class: 'file-link', target: '_blank' %>
    </div>
  <% else %>
    <%= file_fields.input :filename, as: :file, label: false %>
    <%= link_to_remove_association "[remove]".html_safe, file_fields, class: 'text-danger' %>
  <% end %>
</div>

app/views/admin/submissions/dashboard.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @view.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <% @view.filters.each do |filter| %>
      <%= render partial: 'filter', locals: { filter: filter } %>
    <% end %>
  </div>
</div>

app/views/admin/submissions/edit.html.erb
<h2><%= @view.title %></h2>

<%= render partial: 'shared/error_messages', locals: { object: @submission } %>

<%= simple_form_for @submission, url: @view.form_for_url, html: { class: "admin-edit-submission #{@submission.status_class}" } do |f| %>

  <div class="form-section-body">
    <%= f.input :title %>
  </div>

  <div class="form-section-heading" data-toggle="collapse" data-target="#author-information">Author Information
    <span class="hide-show-indicator fa-rotate-90"></span>
  </div>
  <div id="author-information" class="form-section-body collapse in">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <p>
          <%= @submission.author.full_name %><br />
          <%= @submission.author.address_1 %><br />
          <% if @submission.author.address_2.present? %>
            <%= @submission.author.address_2 %><br />
          <% end %>
          <%= @submission.author.city %>, <%= @submission.author.state %> <%= @submission.author.zip %><br />
        </p>
      </div>
      <div class="col-xs-12 col-sm-6">
        <p>
          <strong>Phone:</strong> <%= @submission.author.phone_number %> <br />
          <strong>Alternate email:</strong> <%= @submission.author.alternate_email_address %><br />
        </p>
      </div>
      <div class="col-xs-12">
        <%= link_to edit_admin_author_path(@submission.author), class: 'form-edit-link' do %>
          <span class="fa"></span> Edit Author Information
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-section-heading" data-toggle="collapse" data-target="#program-information">Program Information
    <span class="hide-show-indicator fa-rotate-90"></span>
  </div>
  <div id="program-information" class="form-section-body collapse in">
    <%= f.input :program_id, label: 'Program', collection: Program.all, prompt: "Please Select", input_html: { class: 'can-toggle-selectability' } %>
    <%= f.input :degree_id, label: 'Degree', collection: Degree.all, prompt: "Please Select", input_html: { class: 'can-toggle-selectability' } %>
    <%= f.input :semester, label: 'Semester Intending to Graduate', collection: Submission::SEMESTERS, prompt: "Please Select", input_html: { class: 'can-toggle-selectability' } %>
    <%= f.input :year, label: 'Graduation Year', collection: Submission.years, prompt: "Please Select", input_html: { class: 'can-toggle-selectability' } %>

    <% if @submission.beyond_waiting_for_format_review_response? %>
      <%= link_to '#', class: 'form-edit-link toggle-link' do %>
        <span class="fa"></span> <span class="verb">Edit</span> Program Information
      <% end %>
    <% end %>
  </div>

  <div class="form-section-heading" data-toggle="collapse" data-target="#committee">Committee
    <span class="hide-show-indicator fa-rotate-90"></span>
  </div>
  <div id="committee" class="form-section-body collapse in">
    <%= f.simple_fields_for :committee_members do |cmf| %>
      <fieldset class="committee-member-fields">
        <%= cmf.input :is_advisor, as: :hidden %>
        <%= cmf.input :role, as: :hidden %>
        <div class="row ">
          <div class="col-xs-12">
            <label class="role-label"><%= cmf.object.role %><span title="require" class="required-asterisk">*</span></label>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="input-group">
              <span class="input-group-addon">Name</span>
              <%= cmf.input :name, label: false, input_html: { class: 'can-toggle-editability' } %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="input-group">
              <span class="input-group-addon">Email</span>
              <%= cmf.input :email, label: false, input_html: { class: 'can-toggle-editability' } %>
            </div>
          </div>
        </div>
      </fieldset>
    <% end %>

    <% if @submission.beyond_waiting_for_format_review_response? %>
      <%= link_to '#', class: 'form-edit-link toggle-link' do %>
        <span class="fa"></span> <span class="verb">Edit</span> Committee
      <% end %>
    <% end %>
  </div>

  <div class="form-section-heading" data-toggle="collapse" data-target="#format-review-files">Format Review Information
    <span class="hide-show-indicator fa-rotate-90"></span>
  </div>
  <div id="format-review-files" class="form-section-body collapse in">
    <div class="links cocoon-links">
      <label>Files<span class="required-astrisk">*</span></label>
      <%= link_to_add_association f, :format_review_files,
          class: 'btn btn-default btn-sm can-toggle-clickability',
          data: { association_insertion_node: '#format-review-file-fields', association_insertion_method: 'append' },
          form_name: 'file_fields',
          partial: 'file_fields' do %>
        <span class="glyphicon glyphicon-plus"></span> Additional File
      <% end %>
    </div>
    <div id="format-review-file-fields">
      <%= f.simple_fields_for :format_review_files do |format_review_file| %>
        <%= render 'file_fields', file_fields: format_review_file %>
      <% end %>
    </div>

    <%= f.input :format_review_notes, as: :text, label: "Format Review Notes to Student<span title='require' class='required-asterisk'>*</span>".html_safe, input_html: { class: 'can-toggle-editability' } %>

    <% if @submission.beyond_waiting_for_format_review_response? %>
      <%= link_to '#', class: 'form-edit-link toggle-link' do %>
        <span class="fa"></span> <span class="verb">Edit</span> Format Review Information
      <% end %>
    <% end %>
  </div>

  <%= render partial: 'final_submission_fields', locals: { f: f } if @submission.beyond_waiting_for_format_review_response? %>

  <div class="form-group actions">
    <%= render partial: "admin/submissions/edit_form_actions/#{@view.actions_partial_name}", locals: { f: f } %>
    <%= link_to "Cancel", @view.cancellation_path %>
  </div>

<% end %>

app/views/admin/submissions/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @view.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div id="bulk-actions">
      <h5>Bulk Actions
        <span class="small"><span class="number-of-selected-rows"></span> submissions selected ( <span class="number-of-visible-selected-rows"></span> visible )</span>
      </h5>

      <div class="actions">
        <%= button_to 'Delete selected', admin_delete_submissions_path,
            method: 'delete',
            params: { submission_ids: '' },
            data: { confirm: "Are you sure you want to permanently delete the selected submission(s)?" },
            class: 'btn btn-danger' %>
        <%= button_to 'Release selected for publication', admin_submissions_release_final_submission_approved_path,
            method: 'patch',
            params: { submission_ids: '' },
            data: { confirm: "Are you sure you want to release the selected submission(s)?" },
            class: 'btn btn-primary' if @view.render_release_for_publication_button? %>
      </div>
    </div>
    <div id="row-selection-buttons">
      <button class="select-all-button btn btn-sm btn-default">Select All</button>
      <button class="deselect-all-button btn btn-sm btn-default">Deselect All</button>
      <button class="select-visible-button btn btn-sm btn-default">Select Visible</button>
      <button class="deselect-visible-button btn btn-sm btn-default">Deselect Visible</button>
    </div>
  </div>
</div>


<table id="<%= @view.id %>" class="table table-striped admin-submissions-index datatable" data-ajax-url="<%= admin_submissions_index_path %>">
  <thead>
    <tr>
      <th>&nbsp;</th><%# for the hidden id %>
      <th>&nbsp;</th><%# for the checkbox %>
      <th>Title</th>
      <th>Last Name</th>
      <th>First Name</th>
    </tr>
  </thead>
</table>